// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"database/sql"
)

type Item struct {
	ID           int64
	ParentPath   string
	Name         string
	Path         string
	IsDir        bool
	Size         int64
	ModTime      int64
	Capabilities int64
	IsInsideZip  bool
	IndexedAt    sql.NullTime
}

type ItemsFt struct {
	Name string
	Path string
}
