// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
)

const deleteItemsByPathPrefix = `-- name: DeleteItemsByPathPrefix :exec
DELETE FROM items
WHERE path LIKE ? || '%'
`

func (q *Queries) DeleteItemsByPathPrefix(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteItemsByPathPrefix, dollar_1)
	return err
}

const getItemByPath = `-- name: GetItemByPath :one
SELECT id, parent_path, name, path, is_dir, size, mod_time, capabilities, is_inside_zip, indexed_at FROM items
WHERE path = ? LIMIT 1
`

func (q *Queries) GetItemByPath(ctx context.Context, path string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByPath, path)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ParentPath,
		&i.Name,
		&i.Path,
		&i.IsDir,
		&i.Size,
		&i.ModTime,
		&i.Capabilities,
		&i.IsInsideZip,
		&i.IndexedAt,
	)
	return i, err
}

const listItemsByParent = `-- name: ListItemsByParent :many
SELECT id, parent_path, name, path, is_dir, size, mod_time, capabilities, is_inside_zip, indexed_at FROM items
WHERE parent_path = ?
ORDER BY is_dir DESC, name ASC
`

func (q *Queries) ListItemsByParent(ctx context.Context, parentPath string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByParent, parentPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ParentPath,
			&i.Name,
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.ModTime,
			&i.Capabilities,
			&i.IsInsideZip,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT id, parent_path, name, path, is_dir, size, mod_time, capabilities, is_inside_zip, indexed_at
FROM items
WHERE name LIKE ? OR path LIKE ?
LIMIT 1000
`

type SearchItemsParams struct {
	Name string
	Path string
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.Name, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ParentPath,
			&i.Name,
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.ModTime,
			&i.Capabilities,
			&i.IsInsideZip,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO items (
    parent_path, name, path, is_dir, size, mod_time, capabilities, is_inside_zip
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(path) DO UPDATE SET
    size = excluded.size,
    mod_time = excluded.mod_time,
    capabilities = excluded.capabilities,
    indexed_at = CURRENT_TIMESTAMP
`

type UpsertItemParams struct {
	ParentPath   string
	Name         string
	Path         string
	IsDir        bool
	Size         int64
	ModTime      int64
	Capabilities int64
	IsInsideZip  bool
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertItem,
		arg.ParentPath,
		arg.Name,
		arg.Path,
		arg.IsDir,
		arg.Size,
		arg.ModTime,
		arg.Capabilities,
		arg.IsInsideZip,
	)
	return err
}
